version: '3.8'

services:

  postgres-local:
    image: postgres:17-alpine
    container_name: tronhanh-postgres-local
    restart: unless-stopped
    environment:
      POSTGRES_DB: tronhanh_local
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata_local:/var/lib/postgresql/data

  redis-local:
    image: redis:7-alpine
    container_name: tronhanh-redis-local
    restart: unless-stopped
    ports:
      - "6379:6379"

  redis-ui:
    image: redis/redisinsight:latest
    container_name: tronhanh-redis-ui
    restart: unless-stopped
    ports:
      - "5540:5540"
    depends_on:
      - redis-local
volumes:
  pgdata_local:
