# Spring Application Configuration
spring.profiles.active=${APP_PROFILE}
spring.application.name=tro-nhanh-be

# Server Configuration
server.port=${SERVER_PORT}

# Timezone Configuration (Global UTC)
spring.jackson.time-zone=UTC
spring.jackson.deserialization.fail-on-unknown-properties=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Internationalization (i18n)
spring.messages.basename=i18n/messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false
